### ISSUE TITLE
Remove qualys from subgid & subuid files

### ISSUE THREAD

**Issue by billglick** [ncsa/puppet-profile_audit#21]
The `/etc/subuid` and `/etc/subgid` files for qualys need be emptied out. I think this is an issue for any/most RHEL >=8 nodes that ASD is managing.

Unclear if this an issue of how the user and group are being created. And confused why only the `qualys` user/group shows up (and not other local users e.g. `telegraf`).

See https://jira.ncsa.illinois.edu/browse/SECURITY-1497 for an example.

**Comment by billglick** [comment]
Perhaps it really makes more sense to start specifically managing the subgid/subuid files. We then only configure the specific users/groups that we want in those files. I'm sure this will eventually be an issue for other users/groups that qualys.

**Comment by jakerundall** [comment]
Louis has been working on a script, which could be installed and run via cron by Puppet, to manage these files, e.g., take one or more groups and make sure the members are added to these files in an appropriate fashion.

Here's a related CC ticket: https://jira.ncsa.illinois.edu/browse/NCSACC-946

**Comment by billglick** [comment]
The `qualys` user is getting its subordinate uid & gid set because that account is not a 'system account'. In my testing it appears that normal, non-system accounts get subordinate uid & gid set when added via `useradd`/`groupadd` commands, but 'system account' users do not get added.

According to https://www.cyberciti.biz/faq/create-a-new-user-account-in-centos-7-8-linux/ the following is the command to modify the users:
```
usermod --del-subuids SUB_UID_MIN-SUB_UID_MAX qualys
usermod --del-subgids SUB_GID_MIN-SUB_GID_MAX qualys
```

I am updating [ncsa/profile_audit](https://github.com/ncsa/puppet-profile_audit) again to use an `exec` resource using the above commands: https://github.com/ncsa/puppet-profile_audit/pull/25

----

Once we update the `telegraf` user/group to be consistent across all nodes/clusters ([SVCPLAN-1231](https://jira.ncsa.illinois.edu/browse/SVCPLAN-1231)), we probably will need to add similar logic to [ncsa/profile_monitoring](https://github.com/ncsa/puppet-profile_monitoring) to manage its user/group/subuid/subgid.
