### ISSUE TITLE
Update documentation about Qualys EUS reporting and escalated scans

### ISSUE THREAD

**Issue by billglick** [ncsa/puppet-profile_audit#26]
The README currently lumps usage of both of these together:
```
profile_audit::qualys_eus_reporting::enabled: true
profile_audit::qualys::escalated_scans: true
```
It does not note when we would want to disable the first, but keep the second one enabled.

`qualys_eus_reporting` is only needed on hosts that use EUS but are not setting RHSM to manage the repos (e.g. they point to their own EUS repo mirrors). For hosts that use EUS and use RHSM managed repos, we don’t need the alternate subscription manager script (`qualys_eus_reporting`), but we do need the sudo access for Qualys (`qualys::escalated_scans`).

See discussions in:
- https://git.ncsa.illinois.edu/ici/asd/asd-pup-control/-/merge_requests/168#note_11819
- https://github.com/ncsa/control-repo/pull/133#discussion_r1117209484

**Comment by bsper2** [comment]
Fixed in #27
