### ISSUE TITLE
Update qualys.pp to call sshd::allow_from

### ISSUE THREAD

**Issue by billglick** [ncsa/puppet-profile_audit#3]
https://github.com/ncsa/puppet-profile_audit/blob/a9e4954567d8f7db12eabffdef80593cf6bd9d58/manifests/qualys.pp#L136

profile_audit::qualys should just call https://github.com/ncsa/puppet-sshd/blob/main/manifests/allow_from.pp 
It would remove the access.conf, firewall, sshd_config parts from this class.

**Comment by andylytical** [comment]
ncsa/puppet-sshd/allow_from does all the same parts as lines 109 - 174  
https://github.com/ncsa/puppet-profile_audit/blob/a9e4954567d8f7db12eabffdef80593cf6bd9d58/manifests/qualys.pp#L109-L174

**Comment by billglick** [comment]
I'll try to work on this in the next week or two. While it seems pretty straight forward, I do not want to push this change through today at the end of the week.
