### ISSUE TITLE
Need to ensure perl dependency packages are installed for root equivalence script

### ISSUE THREAD

**Issue by billglick** [ncsa/puppet-profile_audit#9]
Under RedHat:
- `perl-File-HomeDir`
- `perl-Sys-Syslog`

These do not appear to be installed automatically under CentOS 7, but are under RHEL 8.

**Comment by andylytical** [comment]
Suggest better is to re-write the script in BASH (or similar) to remove the dependencies.

There is nothing the script is doing that requires PERL.

**Comment by billglick** [comment]
This was already fixed in https://github.com/ncsa/puppet-profile_audit/pull/10
